---
title: "Project1"
author: "dar7yl"
date: "Tuesday, February 03, 2015"
output: html_document
$Revision: $
---
```{r}
```

---
 Git fork: <https://github.com/dar7yl/ExData_Plotting1>

 Data source: <https://archive.ics.uci.edu/ml/datasets/Individual+household+electric+power+consumption#>
 
```{r check_data}
file.info("exdata_data_household_power_consumption.zip")$ctime
```

## Loading the data
(hint from <http://stackoverflow.com/questions/13022299/specify-date-format-for-colclasses-argument-in-read-table-read-csv/13022441#13022441>)
```{r load_data}

# first check to see if we have cached the file

hpc_cached <- file.access(file.path("data", "hpc.RData"))
if (hpc_cached != 0) 
{
	print("Reading, Subsetting and Cacheing hpc")
	setClass('mericanDate')
	setAs("character","mericanDate", function(from) as.POSIXct(from, format="%d/%m/%Y") )
	
	#setAs("character","mericanTime", function(from) as.POSIXct(from, format="%H:%M:%s") )
	#hpc_Classes <- c( "mericanDate", "mericanTime", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric")
	
	hpc_Classes <- c( "mericanDate", "character", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric")
	
	# I could have read only a subset of the csv but I decided to brute force it in,
	# and then select the dates I'm interested in.
	
	household_power_consumption <- read.csv(file.path("data", "household_power_consumption.txt"), 
			header=TRUE,, sep=";", quote="\"", na.strings="?", colClasses= hpc_Classes,
			nrows=70000,
			stringsAsFactors=FALSE);
	
	summary(household_power_consumption)
	
	dt <- which(household_power_consumption$Date>="2007-02-01" 
					& household_power_consumption$Date <="2007-02-02")
	hpc <- household_power_consumption[dt,]
	
	# convert date+time to datetime column - convolution because POSIXct doesn't support adding.
	hpc$DateTime=as.POSIXct(paste(format(hpc$Date),hpc$Time,sep=" "))
	
	save("hpc", file=file.path("data", "hpc.RData"))
	file.info(file=file.path("data", "hpc.RData"))
}

load( file = file.path("Data", "hpc.RData") )
print("Loaded cached hpc")
summary(hpc)

```

Exploratory plots:

```{r, plot_graphs, echo=FALSE}
plot(hpc$Global_active_power, type="l")
plot(hpc$Voltage, type="l")
plot(hpc$Global_intensity, type="l")

hist( hpc$Global_active_power,
	  main="Global Active Power",
	  xlab="Global Active Power (kilowatts)", ylab="Frequency", 
	  col="red")

rug(hpc$Global_active_power)

with( hpc, {plot(DateTime,Sub_metering_1, col="black", 
					  type="l", ylab="Energy sub metering"); 
				lines(DateTime,Sub_metering_2, col="red"); 
				lines(DateTime,Sub_metering_3, col="blue");
				})
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),
		col=c("black", "red", "blue"), lty=c(1,1,1) )
```

